[package]
name = "vixen_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
futures-lite = "1.12.0"
ndarray = "0.15.4"
serde = "1.0.137"
serde_json = "1.0.81"
noise = "0.7.0"
bevy_flycam = "*"